### ISSUE TITLE
DB Configuration

### ISSUE THREAD

**Issue by marcusmoncayo** [marcusmoncayo/pardotminimoto#1]
change the creds so that postgresql is not using default creds

**Comment by jusroberts** [comment]
define admin. Do you mean a user that can make changes to things through the website?

**Comment by jusroberts** [comment]
Basically, are you looking for an implementation of devise or something that allows logging in and the like?

**Comment by marcusmoncayo** [comment]
Sorry. No admin, just change the creds so that postgresql is not using default creds. Ill change the title

**Comment by jusroberts** [comment]
heroku does this for us: https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-rails
